#spring.application.name=boardserver

spring.profiles.active=local
spring.profiles.group.local=db-local
spring.profiles.include=security


#mysql-local
spring.datasource.driver-class-name=${database.driver}
spring.datasource.url=${database.url}
spring.datasource.username=${database.username}
spring.datasource.password=${database.password}
mybatis.mapper-locations=${mybatis.mapper-locations}
